esther/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from products import views as product_views
from carts import views as cart_views
from orders import views as order_views
from accounts import views as accounts_views
from marketing import views as marketing_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/logout/', accounts_views.LogOutView, name='auth_logout'),
    path('accounts/login/', accounts_views.LogInView, name='auth_login'),
    path('accounts/register/', accounts_views.RegisterView, name='auth_register'),
    path('accounts/address/add/', accounts_views.AddUserAddress, name='add-user-address'),
    path('', product_views.home, name='home'),
    path('s/', product_views.Search, name='search'),
    path('items/', product_views.All, name='items'),
    path('items/<slug:slug>/', product_views.ViewSingle, name='single-item'),
    path('cart/', cart_views.ViewCart, name='cart'),
    path('checkout/', order_views.Checkout, name='checkout'),
    path('orders/', order_views.Orders, name='user-orders'), 
    path('cart/<id>\d+/$', cart_views.RemoveFromCart, name='remove-from-cart'),
    path('cart/<slug:slug>/', cart_views.AddToCart, name='add-to-cart'),   
    path('accounts/activate/<str:activation_key>', accounts_views.ActivationView, name='activate'),
    path('ajax/dismiss_marketing_message/', marketing_views.DismissMarketingMessage, name='dismiss-marketing-message'),
    path('ajax/email_signup/', marketing_views.EmailSignUp, name='ajax_email_signup'),
    path('ajax/add-user-address/', accounts_views.AddUserAddress, name='ajax-add-user-address'),


    #(?P<all_items>.*)
    #(?P<all_items>\d+)
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_save  





def item_image_upload(instance, filename):
	return 'products/%s' %(filename)


# Create your models here.

class Category(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	featured = models.BooleanField(default=None)
	active = models.BooleanField(default=True)


	def __str__(self):
		return self.title

class PopularProducts(models.Model):
	title = models.CharField(max_length=100)
	image = models.ImageField(upload_to=item_image_upload,null=True, blank=True)
	description = models.TextField(null=True, blank=True)
	category = models.ManyToManyField(Category,null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	sale_price = models.FloatField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	update_defaults = models.BooleanField(default=False)


	def __str__(self):
		return self.title

	class Meta:
		unique_together = ('title', 'slug')

	def get_absolute_url(self):
		return reverse('single-popular', kwargs={'slug': self.slug })



class NewArrivals(models.Model):
	title = models.CharField(max_length=100)
	image = models.ImageField(upload_to=item_image_upload,null=True, blank=True)
	description = models.TextField(null=True, blank=True)
	category = models.ManyToManyField(Category,null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	sale_price = models.FloatField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	update_defaults = models.BooleanField(default=False)

	def __str__(self):
		return self.title
	class Meta:
		unique_together = ('title', 'slug')
	def get_absolute_url(self):
		return reverse('single-arrival', kwargs={'slug': self.slug })





	
class Item(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField(null=True, blank=True)
	category = models.ManyToManyField(Category,null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	sale_price = models.FloatField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	update_defaults = models.BooleanField(default=False)


	def __str__(self):
		return self.title


	class meta:
		unique_together = ('title', 'slug')

	def get_price(self):
		return self.price


	def get_absolute_url(self):
		return reverse('single-item', kwargs={'slug': self.slug })



class ItemImage(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	image = models.ImageField(upload_to=item_image_upload)
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)



	def __str__(self):
		return self.item.title


class VariationManager(models.Manager):

	def all(self):
		return super(VariationManager,self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size')

	def colors(self):
		return self.all().filter(category='color')

	def packages(self):
		return self.all().filter(category='package')

VAR_CATEGORIES = (
	('size','size'),
	('color', 'color'),
	('package', 'package'),
)

class Variation(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
	image = models.ForeignKey(ItemImage, null=True, blank=True, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	objects = VariationManager()
	

	def __str__(self):
		return self.title



# T-shirt 5
# Active Wear 6

def item_defaults(sender, instance, created, *args, **kwargs):
	if instance.update_defaults:
		categories = instance.category.all()
		print(categories)
		for cat in categories: 
			print(cat.id)
			if cat.id == 5:#id for tshirt #----> create function for handling all category ids
				small_size = Variation.objects.get_or_create(item=instance,category='size',title='Small')
				medium_size = Variation.objects.get_or_create(item=instance,category='size',title='Medium')
				large_size = Variation.objects.get_or_create(item=instance,category='size',title='Large')


		instance.update_defaults = False
		instance.save()


post_save.connect(item_defaults, sender=Item)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserAddress


User = get_user_model()

class UserAddressForm(forms.ModelForm):
	default = forms.BooleanField(label='Make default')
	class Meta:
		model = UserAddress
		fields = [
		'address',
		'address2',
		'country',
		'zip_code',
		'county',
		'town',
		'phone',
	]


class LogInForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		username = self.cleaned_data.get('username')
		try:
			user = User.objects.get(username=username)
		except User.DoesNotExist:
			raise forms.ValidationError('User not found! Are you sure you are registered?Please go ahead and create an account')
		return username

	def clean_password(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		try:
			user = User.objects.get(username=username)
		except:
			user = None
		if user is not None and not user.check_password(password):
			raise forms.ValidationError('Invalid password! Please try again')
		elif user is None:
			pass
		else:
			return password


class RegistrationForm(forms.ModelForm):
	email = forms.EmailField(label='Email')
	password1 = forms.CharField(label='Set Password', widget=forms.PasswordInput())
	password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ['username','email']

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError('Passwords do not match')
		return password2

	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_count = User.objects.filter(email=email).count()
		if email_count > 0:
			raise forms.ValidationError('This email is already registered, Please check and try again or reset your password')
		return email

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user





	
		

products/views.py
from django.shortcuts import render
from . models import Item, ItemImage, PopularProducts, NewArrivals
from django.http import Http404
from marketing.models import MarketingMessage, Slider
# Create your views here.



def Search(request):
	try:
	    q = request.GET.get('q')
	except:
		q = None
	if q:
		items = Item.objects.filter(title__icontains=q)
		context = {"query": q, "items": items}
		template = 'results.html'
	else:
		template = 'home.html'
		context={}
	
	return render(request, template, context)



def home(request):
	sliders = Slider.objects.all_featured()
	items = Item.objects.all()
	populars = PopularProducts.objects.all()
	arrivals = NewArrivals.objects.all()
	marketing_message = MarketingMessage.objects.all()[0]
	
	context={'items': items,
			'populars': populars,
			'arrivals': arrivals,
			'marketing_message':marketing_message,
			'sliders': sliders
			}
	return render(request, 'index.html', context)



def All(request):
	populars = PopularProducts.objects.all()
	arrivals = NewArrivals.objects.all()
	items = Item.objects.all()
	context={'items': items,
			'populars': populars,
			'arrivals': arrivals

			}

	return render(request, 'all.html', context)


def ViewSingle(request, slug):
	try:

		item = Item.objects.get(slug=slug)
		# images = item.itemimage_set.all()
		images = ItemImage.objects.filter(item=item)
		context_feat ={
				'item': item,
				'images': images,
				}
	except:
		raise Http404

	return render(request, 'single_featured.html', context_feat)

templates/products/activation-complete.html
{% extends 'base.html' %}
{% block content %}

<h1>{{page_message}}</h1>


{% endblock %}

templates/products/all.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

    <!--all products  start -->
    <section id="new-arrivals" class="new-arrivals">

                <div class="container">
            <div class="section-header">
              <!-- <h2>new arrivals</h2>-->        
            </div><!--/.section-header-->
          <div class="new-arrivals-content">
            <div class="row">
              {% for item in items %}
              <div class="col-md-3 col-sm-4">
                  {% if item.itemimage_set %}
                  {% for item in item.itemimage_set.all %}
                  <div class="single-new-arrival">
                    <div class="single-new-arrival-bg">
                      <img src="{{ MEDIA_URL }}{{ item.image.url }}" alt="new-arrivals images">
                      <div class="single-new-arrival-bg-overlay"></div>
                      <div class="sale bg-1">
                        <p>sale</p>
                      </div>
                      <div class="new-arrival-cart">
                        <p>
                          <span class="lnr lnr-cart"></span>
                          <a href="#">add <span>to </span> cart</a>
                        </p>
                        <p class="arrival-review pull-right">
                          <span class="lnr lnr-heart"></span>
                          <span class="lnr lnr-frame-expand"></span>
                        </p>
                      </div>
                    </div>

                  {% endfor %}
                      <h4><a href="/items/{{ item.slug }}">{{ item.title|safe }}</a></h4>
                      
                      <p class="arrival-product-price">Now @ ${{ item.sale_price|safe }}</p>
                      <p class="arrival-product-price">Was <del>${{ item.price }}</del></p>
                      <p>{{ item.description|safe }}</p>
                  </div>         
                {% else %}
                  <div class="single-new-arrival">
                    <div class="single-new-arrival-bg">
                      <img src="static/media/products/images/default.jpg" alt="new-arrivals images">
                      <div class="single-new-arrival-bg-overlay"></div>
                      <div class="sale bg-1">
                        <p>sale</p>
                      </div>
                      <div class="new-arrival-cart">
                        <p>
                          <span class="lnr lnr-cart"></span>
                          <a href="#">add <span>to </span> cart</a>
                        </p>
                        <p class="arrival-review pull-right">
                          <span class="lnr lnr-heart"></span>
                          <span class="lnr lnr-frame-expand"></span>
                        </p>
                      </div>
                    </div>
                    <!-- <h4><a href="/items/{{ item.slug }}">{{ item.title }}</a></h4> -->
                    <h4><a href="#">{{ item.title }}</a></h4>
                    <p class="arrival-product-price">Now @ ${{ item.sale_price }}</p>
                    <p class="arrival-product-price">Was<del>${{ item.price }}</del></p>
                    <p>{{ item.description|safe }}</p>
                  </div>
                {% endif %}
              </div>
              {% endfor %}
              
            </div>
          </div>
        </div><!--/.container-->

    </section><!--/.new-arrivals-->
    <!--all products end -->


{% endblock %}

templates/products/modal.html
<div class="modal fade" id="marketingModal">
  <form method="POST" action="{% url 'ajax_email_signup' %}" id="sendForm">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Subscribe for latest fashion updates</h4>
      </div>
      <div class="modal-body">
        <!-- <input class="form-control" type="text" placeholder="Enter your email"/> -->
        <p id="modalMessage"></p>

        <input id="id_email" class="form-control" maxlength="200" type="email" name="email" placeholder="Enter your email">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-success" id="sendMarketingForm">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
  </form>
</div><!-- /.modal -->

templates/products/results.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1> Searched for: {{ query }}</h1>

{{ items }}

<table class="table">
	<thead>
		<th></th>
		<th>Item</th>
	</thead>

	<tbody>
		{% for item in items %}
		<tr>
			<td style="width: 160px; height: 160px;">
				{% if item.itemimage_set.all %}
				  {% for item in item.itemimage_set.all %}
                    {% if item.featured %}

<div style="width: 100%; height: 100%; background-image:url('{{ MEDIA_URL }}{{ item.image.url }}'); background-size:cover; background-repeat: no-repeat; background-position: center;"></div>

                    {% endif %}
                  {% endfor %}


				{% else %}
			<div style="width: 100%; height: 100%; background-image: url('{% static 'img/placeholder.svg' %}'); background-size:cover; background-repeat: no-repeat; background-position: center;"></div>
				{% endif %}
			</td>
			<td><a href="{{ item.get_absolute_url }}">{{ item }}</a></td>		
			
		</tr>
		{% endfor %}

	</tbody>

</table>

{% endblock %}

templates/products/single.html
{% extends 'base.html' %}

<div class="page-header">	
	<h1>{{ item.title }}</h1>
</div>
{% block content %}

<div class="row">
			<div class="col-sm-4">     
		     {% for image in images %}

		        {% if image.featured %}
		        <div class="col-xs-12">
		        <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}"/>
		        <hr/>
		        </div>
		        {% endif %}
		     {% endfor %}

		     {% for image in images %}

		       {% if not image.featured %}
		    <div class="col-xs-6">
		    	<a href="" class="thumbnail"></a>
		    	<img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}">
		    </div>
		    {% endif %}
		    {% endfor %}
		  </div>
		  <div class="col-sm-8">
		    <div class="col-sm-8 pull-left">
            	<h1>{{ item.title }}
             		
            	</h1>
        	</div>
        		<div class="col-sm-4 pull-right">
	             	<form class="form pull-right" method="POST" action="{% url 'add-to-cart' item.slug %}">
	             		{% csrf_token %}
	             		<input class="btn btn-default btn-block" type="submit" value="Add to Cart"/>
	             		<input class="form-control" type="number" name="Qty" value="1"/>
	             
	             	{% if item.variation_set.all %}

	             		{% if item.variation_set.sizes %}
		             		<select class="form-control" name="size">
		             			{% for item in item.variation_set.sizes %}
		             				<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
		             			{% endfor %}
		             		</select>
	             		{% endif %}

		             	{% if item.variation_set.colors %}
		             		<select class="form-control" name="color">
		             			{% for item in item.variation_set.colors %}
		             				<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
		             			{% endfor %}	
		             		</select>
	             		{% endif %}

	             	{% endif %}   		
	             	</form>
             	</div>
             <div class="col-sm-12"></div>
	             <hr/>
	             Price: ${{ item.price }}<br/>
	             Shipping: Free with purchase above $100
	             <hr/>
             </div>
	             <div class="col-sm-12">
	             	{{ item.description|linebreaks }}
	             </div>

		    </div>	
</div>
{% endblock %}

templates/products/single_arrival.html
{% extends 'base.html' %}

{% block content %}



{% if arrival %}
<div class="page-header">	
	<h1>{{ arrival.title }}</h1>
</div>
<div class="row">
			<div class="col-sm-4">     

		        {% if image.featured %}
		        <div class="col-xs-12">
		        <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}"/>
		        <hr/>
		        </div>
		        {% endif %}
		  </div>
		  <div class="col-sm-8">
		    <div class="col-sm-8 pull-left">
            	<h1>{{ arrival.title }}</h1>             		           	
        	</div>
        		<div class="col-sm-4 pull-right">
	             	<form class="form pull-right" method="POST" action="{% url 'add-to-cart' item.slug %}">
	             		{% csrf_token %}
	             		<input class="btn btn-default btn-block" type="submit" value="Add to Cart"/>
	             		<input class="form-control" type="number" name="Qty" value="1"/>
	             
	             	{% if arrival.variation_set.all %}

	             		{% if arrival.variation_set.sizes %}
		             		<select class="form-control" name="size">
		             			{% for v in arrival.variation_set.sizes %}
		             				<option value="{{ item.title|lower }}">{{ v.title|capfirst }}</option>
		             			{% endfor %}
		             		</select>
	             		{% endif %}

		             	{% if arrival.variation_set.colors %}
		             		<select class="form-control" name="color">
		             			{% for v in arrival.variation_set.colors %}
		             				<option value="{{ item.title|lower }}">{{ v.title|capfirst }}</option>
		             			{% endfor %}	
		             		</select>
	             		{% endif %}

	             	{% endif %}   		
	             	</form>
             	</div>
             <div class="col-sm-12"></div>
	             <hr/>
	             Price: ${{ arrival.price }}<br/>
	             Shipping: Free with purchase above $100
	             <hr/>
             </div>
	             <div class="col-sm-12">
	             	{{ arrival.description|linebreaks }}
	             </div>

		    </div>	
</div>
{% endif %}



{% endblock %}

templates/products/single_featured.html
{% extends 'base.html' %}

{% block content %}



{% if item %}
<div class="page-header">	
	<h1>{{ item.title }}</h1>
</div>
<div class="row">
			<div class="col-sm-4">     
		     {% for image in images %}

		        {% if image.featured %}
		        <div class="col-xs-12">
		        <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}"/>
		        <hr/>
		        </div>
		        {% endif %}
		     {% endfor %}
		  </div>
		  <div class="col-sm-8">
		    <div class="col-sm-8 pull-left">
            	<h1>{{ item.title }}</h1>             		           	
        	</div>
        		<div class="col-sm-4 pull-right">
	             	<form class="form pull-right" method="POST" action="{% url 'add-to-cart' item.slug %}">
	             		{% csrf_token %}
	             		<input class="btn btn-default btn-block" type="submit" value="Add to Cart"/>
	             		<input class="form-control" type="number" name="Qty" value="1"/>
	             
	             	{% if item.variation_set.all %}

	             		{% if item.variation_set.sizes %}
		             		<select class="form-control" name="size">
		             			{% for item in item.variation_set.sizes %}
		             				<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
		             			{% endfor %}
		             		</select>
	             		{% endif %}

		             	{% if item.variation_set.colors %}
		             		<select class="form-control" name="color">
		             			{% for item in item.variation_set.colors %}
		             				<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
		             			{% endfor %}	
		             		</select>
	             		{% endif %}

	             	{% endif %}   		
	             	</form>
             	</div>
             <div class="col-sm-12"></div>
	             <hr/>
	             Price: ${{ item.price }}<br/>
	             Shipping: Free with purchase above $100
	             <hr/>
             </div>
	             <div class="col-sm-12">
	             	{{ item.description|linebreaks }}
	             </div>

		    </div>	
</div>
{% endif %}

































{% endblock %}

templates/products/single_popular.html
{% extends 'base.html' %}

{% block content %}



{% if popular %}
<div class="page-header">	
	<h1>{{ popular.title }}</h1>
</div>
<div class="row">
			<div class="col-sm-4">     

		        {% if image.featured %}
		        <div class="col-xs-12">
		        <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}"/>
		        <hr/>
		        </div>
		        {% endif %}
		  </div>
		  <div class="col-sm-8">
		    <div class="col-sm-8 pull-left">
            	<h1>{{ popular.title }}</h1>             		           	
        	</div>
        		<div class="col-sm-4 pull-right">
	             	<form class="form pull-right" method="POST" action="{% url 'add-to-cart' item.slug %}">
	             		{% csrf_token %}
	             		<input class="btn btn-default btn-block" type="submit" value="Add to Cart"/>
	             		<input class="form-control" type="number" name="Qty" value="1"/>
	             
	             	{% if popular.variation_set.all %}

	             		{% if popular.variation_set.sizes %}
		             		<select class="form-control" name="size">
		             			{% for v in popular.variation_set.sizes %}
		             				<option value="{{ item.title|lower }}">{{ v.title|capfirst }}</option>
		             			{% endfor %}
		             		</select>
	             		{% endif %}

		             	{% if popular.variation_set.colors %}
		             		<select class="form-control" name="color">
		             			{% for v in popular.variation_set.colors %}
		             				<option value="{{ item.title|lower }}">{{ v.title|capfirst }}</option>
		             			{% endfor %}	
		             		</select>
	             		{% endif %}

	             	{% endif %}   		
	             	</form>
             	</div>
             <div class="col-sm-12"></div>
	             <hr/>
	             Price: ${{ popular.price }}<br/>
	             Shipping: Free with purchase above $100
	             <hr/>
             </div>
	             <div class="col-sm-12">
	             	{{ popular.description|linebreaks }}
	             </div>

		    </div>	
</div>
{% endif %}



{% endblock %}